name: Update BBC Tech News Changelog

on:
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  update-changelog:
    uses: uibm/technology/.github/workflows/update-changelog.yml@main
    secrets: inherit
