name: Update BBC Tech News Changelog

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */23 * * *'  # Every 23 hours

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  update-changelog:
    uses: uibm/technology/.github/workflows/update-changelog.yml@main
    secrets: inherit
