name: Update BBC Tech News Changelog

on:
  schedule:
    - cron: '* * * * *'  # Run every minute
  workflow_dispatch:      # Allow manual trigger

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    concurrency: 
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # First create requirements.txt
      - name: Create requirements file
        run: |
          cat > requirements.txt << 'EOF'
          feedparser==6.0.11
          markdown==3.5.2
          PyYAML==6.0.1
          python-dateutil==2.8.2
          pytz==2024.1
          EOF

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch and process RSS feed
        run: |
          cat > update_changelog.py << 'EOF'
          import feedparser
          import yaml
          from datetime import datetime
          import os
          from dateutil import parser
          import pytz
          import time

          def load_existing_entries():
              if os.path.exists('_data/changelog.yml'):
                  with open('_data/changelog.yml', 'r', encoding='utf-8') as f:
                      try:
                          return yaml.safe_load(f) or []
                      except yaml.YAMLError:
                          return []
              return []

          def fetch_bbc_feed():
              max_retries = 3
              for attempt in range(max_retries):
                  try:
                      feed = feedparser.parse('https://feeds.bbci.co.uk/news/technology/rss.xml')
                      if hasattr(feed, 'status') and feed.status == 200:
                          return feed.entries
                      time.sleep(2 ** attempt)
                  except Exception as e:
                      if attempt == max_retries - 1:
                          raise e
                      time.sleep(2 ** attempt)
              return []

          def create_changelog_entry(entry):
              return {
                  'title': entry.title,
                  'link': entry.link,
                  'published': parser.parse(entry.published).astimezone(pytz.UTC).isoformat(),
                  'summary': entry.summary,
                  'guid': entry.guid
              }

          def update_changelog():
              os.makedirs('_data', exist_ok=True)
              
              existing_entries = load_existing_entries()
              existing_guids = {entry['guid'] for entry in existing_entries}
              
              new_entries = fetch_bbc_feed()
              
              updates = []
              for entry in new_entries:
                  if entry.guid not in existing_guids:
                      updates.append(create_changelog_entry(entry))
              
              if not updates:
                  print("No new entries found")
                  return False
              
              all_entries = updates + existing_entries
              all_entries.sort(key=lambda x: x['published'], reverse=True)
              all_entries = all_entries[:100]
              
              with open('_data/changelog.yml', 'w', encoding='utf-8') as f:
                  yaml.dump(all_entries, f, allow_unicode=True, sort_keys=False)
              
              with open('index.html', 'w', encoding='utf-8') as f:
                  f.write('''
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <meta http-equiv="refresh" content="60">
              <title>BBC Technology News Changelog</title>
              <style>
                  body {
                      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
                      line-height: 1.6;
                      max-width: 800px;
                      margin: 0 auto;
                      padding: 20px;
                      background: #f5f5f5;
                  }
                  .entry {
                      background: white;
                      padding: 20px;
                      margin-bottom: 20px;
                      border-radius: 8px;
                      box-shadow: 0 2px 4px rgba(0,0,0,0.1);
                      transition: transform 0.2s ease;
                  }
                  .entry:hover {
                      transform: translateY(-2px);
                      box-shadow: 0 4px 8px rgba(0,0,0,0.1);
                  }
                  .entry h2 {
                      margin-top: 0;
                      color: #2c3e50;
                  }
                  .entry-meta {
                      color: #666;
                      font-size: 0.9em;
                      margin-bottom: 10px;
                  }
                  a {
                      color: #3498db;
                      text-decoration: none;
                  }
                  a:hover {
                      text-decoration: underline;
                  }
                  .header {
                      text-align: center;
                      margin-bottom: 40px;
                  }
                  .last-updated {
                      text-align: center;
                      color: #666;
                      margin-bottom: 20px;
                      font-size: 0.9em;
                  }
                  .auto-refresh {
                      text-align: center;
                      color: #666;
                      font-size: 0.8em;
                      margin-bottom: 30px;
                  }
                  @media (max-width: 600px) {
                      body {
                          padding: 10px;
                      }
                      .entry {
                          padding: 15px;
                      }
                  }
              </style>
          </head>
          <body>
              <div class="header">
                  <h1>BBC Technology News Changelog</h1>
              </div>
              <div class="last-updated">
                  Last updated: ''' + datetime.now().strftime('%Y-%m-%d %H:%M:%S UTC') + '''
              </div>
              <div class="auto-refresh">
                  Page auto-refreshes every minute
              </div>
          ''')
                  
                  for entry in all_entries:
                      published = parser.parse(entry['published']).strftime('%Y-%m-%d %H:%M:%S UTC')
                      f.write(f'''
              <div class="entry">
                  <h2><a href="{entry['link']}">{entry['title']}</a></h2>
                  <div class="entry-meta">Published: {published}</div>
                  <div class="entry-content">
                      {entry['summary']}
                  </div>
              </div>
          ''')
                  
                  f.write('''
              </body>
          </html>
          ''')
              
              return True

          if __name__ == '__main__':
              update_changelog()
          EOF

          python update_changelog.py

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Commit changes
        run: |
          git config --local user.email "ujjwal.kumar1@ibm.com"
          git config --local user.name "ujjwal-ibm"
          git add _data/changelog.yml index.html requirements.txt
          git diff --quiet && git diff --staged --quiet || git commit -m "Update changelog with latest BBC Tech news"
          git push